on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: demoaksnov
  CLUSTER_NAME: tstk8cluster
  CLUSTER_RESOURCE_GROUP: tstk8grp
  NAMESPACE: test
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Create imagepullsecret for Azure Container registry (ACR)
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
        
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
          version: v3.4.1
    
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.1.0
      with:
          charts_dir: charts
      


    
    # Deploy app to AKS
    #- uses: azure/k8s-deploy@v1
    #  with:
    #    manifests: |
    #      manifests/azure-vote-all-in-one-redis.yaml
    #    images: |
    #      ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
    #    imagepullsecrets: |
    #      ${{ env.REGISTRY_NAME }}-registry-connection
    #    namespace: ${{ env.NAMESPACE }}
